//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eCoreTestChallenge.Data {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppLabels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppLabels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("eCoreTestChallenge.Data.AppLabels", typeof(AppLabels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing Details.
        /// </summary>
        internal static string Billing_Details {
            get {
                return ResourceManager.GetString("Billing_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking Code.
        /// </summary>
        internal static string Booking_Code {
            get {
                return ResourceManager.GetString("Booking_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check-In.
        /// </summary>
        internal static string Check_In {
            get {
                return ResourceManager.GetString("Check_In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check-Out.
        /// </summary>
        internal static string Check_Out {
            get {
                return ResourceManager.GetString("Check_Out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit Now.
        /// </summary>
        internal static string Deposit_Now {
            get {
                return ResourceManager.GetString("Deposit_Now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due Date:.
        /// </summary>
        internal static string Due_Date_ {
            get {
                return ResourceManager.GetString("Due_Date_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Date:.
        /// </summary>
        internal static string Invoice_Date_ {
            get {
                return ResourceManager.GetString("Invoice_Date_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Details.
        /// </summary>
        internal static string Invoice_Details {
            get {
                return ResourceManager.GetString("Invoice_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice List.
        /// </summary>
        internal static string Invoice_List {
            get {
                return ResourceManager.GetString("Invoice_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room.
        /// </summary>
        internal static string Room {
            get {
                return ResourceManager.GetString("Room", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax&amp;VAT.
        /// </summary>
        internal static string Tax_VAT {
            get {
                return ResourceManager.GetString("Tax_VAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Amount.
        /// </summary>
        internal static string Total_Amount {
            get {
                return ResourceManager.GetString("Total_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Stay Amount.
        /// </summary>
        internal static string Total_Stay_Amount {
            get {
                return ResourceManager.GetString("Total_Stay_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Stay Count.
        /// </summary>
        internal static string Total_Stay_Count {
            get {
                return ResourceManager.GetString("Total_Stay_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong username or password.
        /// </summary>
        internal static string Wrong_username_or_password {
            get {
                return ResourceManager.GetString("Wrong_username_or_password", resourceCulture);
            }
        }
    }
}
